version: 0.2

env:
  parameter-store:
      DOCKER_USERNAME: /myapp/docker-credentials/username
      DOCKER_PASSWORD: /myapp/docker-credentials/password
      DOCKER_URL: /myapp/docker-registry/url
phases:
  install:
    runtime-versions:
       python: 3.11
  pre_build:
    commands:
       - echo "Logging in to Docker Hub..."
       - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_URL
       - echo "Installing dependencies..."
       - pip install -r sample-python-app/requirements.txt
  build:
    commands:
       - cd sample-python-app/
       - echo "Building Docker Image"
       - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
       - docker tag $IMAGE_REPO_NAME $DOCKER_USERNAME/$IMAGE_REPO_NAME:$IMAGE_TAG
       - docker images
  post_build:
    commands:
       - echo "Pushing the Docker Image..."
       - docker push $IMAGE_REPO_NAME:$IMAGE_TAG 
       - echo "Build is Successfull..."
